<<<<<<< HEAD
#ifndef STAMP_SERIALIZE_SERIALIZE_H
#define STAMP_SERIALIZE_SERIALIZE_H



#endif // STAMP_SERIALIZE_SERIALIZE_H
=======
#ifndef STAMP_SERIALIZE_SERIALIZE_H
#define STAMP_SERIALIZE_SERIALIZE_H



#endif // STAMP_SERIALIZE_SERIALIZE_H
>>>>>>> asdad
